---
- hosts: all
  roles:
  - role: auth

  tasks: 
    - name: show containers
      command: 'curl -s -k --cert mylxd.crt --key mylxd.key {{ LXD_HOST }}/1.0/containers'
      register: show_container

    - debug:
        msg: "{{  show_container.stdout }}"
