---
- hosts: all
  roles:
  - role: auth

  tasks: 
    - name: show networks
      command: 'curl -s -k --cert mylxd.crt --key mylxd.key {{ LXD_HOST }}/1.0/networks'
      register: show_networks

    - debug:
        msg: "{{  show_networks.stdout }}"
