---
- hosts: all
  roles:
  - role: auth

  tasks: 
    - name: show profiles
      command: 'curl -s -k --cert mylxd.crt --key mylxd.key {{ LXD_HOST }}/1.0/profiles'
      register: show_profiles

    - debug:
        msg: "{{  show_profiles.stdout }}"
